---
controller_inventory_sources:
  - name: controller_config_source
    source: scm
    source_project: config_as_code
    source_path: "inventory.yml"
    inventory: config_as_code
    overwrite: true
    overwrite_vars: true
...