---
- name: Configure private automation hub after installation
  hosts: all
  gather_facts: false
  connection: local
  vars_files:
    - "../vault.yml"
  tasks:


    - name: Include repository role
      ansible.builtin.include_role:
        name: infra.ah_configuration.repository

    - name: Include repository sync role
      ansible.builtin.include_role:
        name: infra.ah_configuration.repository_sync

    - name: Include group role
      ansible.builtin.include_role:
        name: infra.ah_configuration.group

    - name: Include user role
      ansible.builtin.include_role:
        name: infra.ah_configuration.user
...
